### ISSUE TITLE
anioły = demons

### ISSUE THREAD

**Issue by and09** [przemub/polinux#6]
Wj. polskim anioly mogą mieć pozytywna jak i negatywna konotację, demony zawsze negatywną (nie chodzi nawet o kwestie religijne). Taka zależność nie występuje właściwie w j. angielskim.

Proponuje tłumaczyć demony jako anioły.

**Comment by przemub** [comment]
Zapraszam do dyskusji na wiki :)
https://polinux.pl/index.php/S%C5%82ownictwo/J%C4%85dro
